sudo: false

addons:
  apt:
    packages:
    - texlive-full
    - texlive-binaries
    - texlive-latex-extra
    - texlive-latex-recommended
    - latexmk
    - hunspell
    - python
    - python-pip

install:
- cd $TRAVIS_BUILD_DIR/mtheme/source
- latex beamerthememetropolis.ins
- mv *.sty $TRAVIS_BUILD_DIR/tex
- pip install Pygments

script:
- cd $TRAVIS_BUILD_DIR/tex
- latexmk --shell-escape -pdf presentation.tex
- find $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ncbx0wlHyXfUB8qvVdEzejbrTOS4cS2CIkcsDb2SHyoK+7BFqoDmu5Zc7/k5Q1IwgTO3ZKGTvqRhHcSvo9pFqDURM3EwPtgYl+3VIX5GfB8dTEsVoigGBZCUKwZXyGA/Z+j8stMyA4xKzOhAuU8GTfeVVcebmflINd/IEEZLHv1qUzZ15jzNo7O7ufsmZBkyhEGFrmZMAgQSi6vOiMH9p6Mz5JaQxzh3CJvJcGxsjY3O2PKUTerlwp65BPBAJVSPIwQ74eVMrK03khfdvuID1OVbuNiaDgejqON8qGni0dy83YtCRVfNJ8iJ+otectRa8RvayfZEYvSUC67IKAMTEkSwVqLxYpXU7qjOW34EG35P6a2EuLEruDhEN86P8R1yThIJYCaaLn8d0iLmi7xmYlOq8t3qgB4yfQMCq61RzumHk40dg7I/UZrk4aAzFndEtJntKBZGNLCJthXCyoOB481oYJikGcE44Me7Hl/FoIpdA/ryIp2gcC2iLe5HBuMhlUZB+Bzbclt9DVzsTsaNs2abI80RehQrqqvyZd1SlJdG56T2TsuoVWwxkVhzuP96/40dZmHF3B5McN/Z7bclvjpd977DPmXwOtOZI8PCzGdrj3hYmy8q9gaRwJ8TFltQHmgGXGALS5czcORWlbtKGz3I2+F0bv89+0OlL6S8mM4=
  file: $TRAVIS_BUILD_DIR/tex/presentation.pdf
  on:
    tags: true
    repo: nnadeau/kuka-lbr-intro

notifications:
  email: false
